\c bregmotors

INSERT INTO Usluge (uslugaNaziv) VALUES
('Zamjena ulja'),
('Balansiranje guma'),
('Servis kočnica'),
('Dijagnostika motora'),
('Promjena filtera zraka'),
('Zamjena akumulatora'),
('Popravak klima uređaja'),
('Zamjena svjećica'),
('Servis mjenjača'),
('Ostalo');


INSERT INTO Serviser (imeServiser, prezimeServiser, email, voditeljServisa)
VALUES
('Antonio', 'Valec', 'antonio.valec04@gmail.com', TRUE),
('Ivan', 'Horvat', 'ivan.horvat@gmail.com', FALSE),
('Petra', 'Klarić', 'petra.klaric@gmail.com', FALSE),
('Luka', 'Babić', 'luka.babic@gmail.com', FALSE),
('Ana', 'Radić', 'ana.radic@gmail.com', FALSE);

INSERT INTO Model (modelNaziv, markaNaziv) VALUES
('A3', 'Audi'),
('A4', 'Audi'),
('A6', 'Audi'),
('Q3', 'Audi'),
('Q5', 'Audi'),
('Q7', 'Audi'),
('1 Series', 'BMW'),
('3 Series', 'BMW'),
('5 Series', 'BMW'),
('X1', 'BMW'),
('X3', 'BMW'),
('X5', 'BMW'),
('Focus', 'Ford'),
('Fiesta', 'Ford'),
('Mondeo', 'Ford'),
('Kuga', 'Ford'),
('Puma', 'Ford'),
('Civic', 'Honda'),
('Accord', 'Honda'),
('CR-V', 'Honda'),
('Jazz', 'Honda'),
('Elantra', 'Hyundai'),
('Tucson', 'Hyundai'),
('Santa Fe', 'Hyundai'),
('i20', 'Hyundai'),
('i30', 'Hyundai'),
('Sportage', 'Kia'),
('Ceed', 'Kia'),
('Rio', 'Kia'),
('Stonic', 'Kia'),
('Optima', 'Kia'),
('Mazda3', 'Mazda'),
('Mazda6', 'Mazda'),
('CX-3', 'Mazda'),
('CX-5', 'Mazda'),
('GLA', 'Mercedes'),
('GLC', 'Mercedes'),
('C-Class', 'Mercedes'),
('E-Class', 'Mercedes'),
('S-Class', 'Mercedes'),
('A-Class', 'Mercedes'),
('Outlander', 'Mitsubishi'),
('ASX', 'Mitsubishi'),
('Lancer', 'Mitsubishi'),
('Pajero', 'Mitsubishi'),
('Juke', 'Nissan'),
('Qashqai', 'Nissan'),
('Micra', 'Nissan'),
('Leaf', 'Nissan'),
('X-Trail', 'Nissan'),
('208', 'Peugeot'),
('308', 'Peugeot'),
('3008', 'Peugeot'),
('508', 'Peugeot'),
('Partner', 'Peugeot'),
('Clio', 'Renault'),
('Megane', 'Renault'),
('Captur', 'Renault'),
('Kadjar', 'Renault'),
('Talisman', 'Renault'),
('Ibiza', 'Seat'),
('Leon', 'Seat'),
('Ateca', 'Seat'),
('Tarraco', 'Seat'),
('Fabia', 'Škoda'),
('Octavia', 'Škoda'),
('Superb', 'Škoda'),
('Karoq', 'Škoda'),
('Kamiq', 'Škoda'),
('Impreza', 'Subaru'),
('Forester', 'Subaru'),
('Outback', 'Subaru'),
('Yaris', 'Toyota'),
('Corolla', 'Toyota'),
('Camry', 'Toyota'),
('RAV4', 'Toyota'),
('C-HR', 'Toyota'),
('Auris', 'Toyota'),
('Golf', 'Volkswagen'),
('Polo', 'Volkswagen'),
('Passat', 'Volkswagen'),
('Tiguan', 'Volkswagen'),
('Touareg', 'Volkswagen'),
('T-Roc', 'Volkswagen'),
('Up!', 'Volkswagen'),
('V40', 'Volvo'),
('S60', 'Volvo'),
('S90', 'Volvo'),
('XC40', 'Volvo'),
('XC60', 'Volvo'),
('XC90', 'Volvo'),
('Giulia', 'Alfa Romeo'),
('Stelvio', 'Alfa Romeo'),
('Model 3', 'Tesla'),
('Model S', 'Tesla'),
('Model X', 'Tesla'),
('Model Y', 'Tesla'),
('500', 'Fiat'),
('Panda', 'Fiat'),
('Tipo', 'Fiat'),
('Doblo', 'Fiat'),
('Punto', 'Fiat');