INSERT INTO Model (modelNaziv, markaNaziv) VALUES
('A3', 'Audi'),
('A4', 'Audi'),
('A6', 'Audi'),
('Q3', 'Audi'),
('Q5', 'Audi'),
('Q7', 'Audi'),
('1 Series', 'BMW'),
('3 Series', 'BMW'),
('5 Series', 'BMW'),
('X1', 'BMW'),
('X3', 'BMW'),
('X5', 'BMW'),
('Focus', 'Ford'),
('Fiesta', 'Ford'),
('Mondeo', 'Ford'),
('Kuga', 'Ford'),
('Puma', 'Ford'),
('Civic', 'Honda'),
('Accord', 'Honda'),
('CR-V', 'Honda'),
('Jazz', 'Honda'),
('Elantra', 'Hyundai'),
('Tucson', 'Hyundai'),
('Santa Fe', 'Hyundai'),
('i20', 'Hyundai'),
('i30', 'Hyundai'),
('Sportage', 'Kia'),
('Ceed', 'Kia'),
('Rio', 'Kia'),
('Stonic', 'Kia'),
('Optima', 'Kia'),
('Mazda3', 'Mazda'),
('Mazda6', 'Mazda'),
('CX-3', 'Mazda'),
('CX-5', 'Mazda'),
('GLA', 'Mercedes'),
('GLC', 'Mercedes'),
('C-Class', 'Mercedes'),
('E-Class', 'Mercedes'),
('S-Class', 'Mercedes'),
('A-Class', 'Mercedes'),
('Outlander', 'Mitsubishi'),
('ASX', 'Mitsubishi'),
('Lancer', 'Mitsubishi'),
('Pajero', 'Mitsubishi'),
('Juke', 'Nissan'),
('Qashqai', 'Nissan'),
('Micra', 'Nissan'),
('Leaf', 'Nissan'),
('X-Trail', 'Nissan'),
('208', 'Peugeot'),
('308', 'Peugeot'),
('3008', 'Peugeot'),
('508', 'Peugeot'),
('Partner', 'Peugeot'),
('Clio', 'Renault'),
('Megane', 'Renault'),
('Captur', 'Renault'),
('Kadjar', 'Renault'),
('Talisman', 'Renault'),
('Ibiza', 'Seat'),
('Leon', 'Seat'),
('Ateca', 'Seat'),
('Tarraco', 'Seat'),
('Fabia', 'Škoda'),
('Octavia', 'Škoda'),
('Superb', 'Škoda'),
('Karoq', 'Škoda'),
('Kamiq', 'Škoda'),
('Impreza', 'Subaru'),
('Forester', 'Subaru'),
('Outback', 'Subaru'),
('Yaris', 'Toyota'),
('Corolla', 'Toyota'),
('Camry', 'Toyota'),
('RAV4', 'Toyota'),
('C-HR', 'Toyota'),
('Auris', 'Toyota'),
('Golf', 'Volkswagen'),
('Polo', 'Volkswagen'),
('Passat', 'Volkswagen'),
('Tiguan', 'Volkswagen'),
('Touareg', 'Volkswagen'),
('T-Roc', 'Volkswagen'),
('Up!', 'Volkswagen'),
('V40', 'Volvo'),
('S60', 'Volvo'),
('S90', 'Volvo'),
('XC40', 'Volvo'),
('XC60', 'Volvo'),
('XC90', 'Volvo'),
('Giulia', 'Alfa Romeo'),
('Stelvio', 'Alfa Romeo'),
('Model 3', 'Tesla'),
('Model S', 'Tesla'),
('Model X', 'Tesla'),
('Model Y', 'Tesla'),
('500', 'Fiat'),
('Panda', 'Fiat'),
('Tipo', 'Fiat'),
('Doblo', 'Fiat'),
('Punto', 'Fiat');

INSERT INTO Serviser (imeServiser, prezimeServiser, email, voditeljServisa)
VALUES
('Antonio', 'Valec', 'antonio.valec88@gmail.com', TRUE),
('Ivan', 'Horvat', 'ivan.horvat@gmail.com', FALSE),
('Petra', 'Klarić', 'petra.klaric@gmail.com', FALSE),
('Luka', 'Babić', 'luka.babic@gmail.com', FALSE),
('Ana', 'Radić', 'ana.radic@gmail.com', FALSE);

INSERT INTO Usluge (uslugaNaziv) VALUES
('Zamjena ulja'),
('Balansiranje guma'),
('Servis kočnica'),
('Dijagnostika motora'),
('Promjena filtera zraka'),
('Zamjena akumulatora'),
('Popravak klima uređaja'),
('Zamjena svjećica'),
('Servis mjenjača'),
('Ostalo');


INSERT INTO Vozilo (registracija, idModel, godinaProizv)
VALUES
('ZG123AA', 1, 2018),
('ZG456BB', 2, 2017),
('ST789CC', 3, 2020),
('RI101DD', 4, 2022),
('ZG202EE', 1, 2019);

INSERT INTO Klijent (imeKlijent, prezimeKlijent, email, slikaUrl)
VALUES
('Marko', 'Horvat', 'marko.horvat@example.com', 'https://example.com/img1.jpg'),
('Ivana', 'Kovač', 'ivana.kovac@example.com', 'https://example.com/img2.jpg'),
('Petar', 'Marić', 'petar.maric@example.com', 'https://example.com/img3.jpg'),
('Ana', 'Babić', 'ana.babic@example.com', 'https://example.com/img4.jpg'),
('Luka', 'Novak', 'luka.novak@example.com', 'https://example.com/img5.jpg');

INSERT INTO ZamjenskoVozilo (idModel, datumPreuzimanja, datumVracanja) VALUES
(3,  NULL, NULL),
(7,  NULL, NULL),
(12, NULL, NULL),
(18, NULL, NULL),
(21, NULL, NULL),
(25, NULL, NULL),
(30, NULL, NULL),
(33, NULL, NULL),
(37, NULL, NULL),
(40, NULL, NULL),
(44, NULL, NULL),
(49, NULL, NULL),
(52, NULL, NULL),
(56, NULL, NULL),
(61, NULL, NULL),
(67, NULL, NULL),
(73, NULL, NULL),
(80, NULL, NULL),
(95, NULL, NULL),
(100, NULL, NULL);

INSERT INTO Nalog (datumVrijemeTermin, datumVrijemeZavrsenPopravak, status, datumVrijemeAzuriranja, idKlijent, idVozilo, idUsluga, idServiser)
VALUES
('2025-11-10 09:00:00', NULL, 0, CURRENT_TIMESTAMP, 1, 1, 1, 1),
('2025-11-11 10:30:00', NULL, 0, CURRENT_TIMESTAMP, 2, 2, 1, 1),
('2025-11-12 08:15:00', NULL, 1, CURRENT_TIMESTAMP, 3, 3, 1, 1),
('2025-11-13 14:00:00', NULL, 2, CURRENT_TIMESTAMP, 4, 4, 1, 1),
('2025-11-14 11:45:00', NULL, 0, CURRENT_TIMESTAMP, 5, 5, 1, 1);